# Recommendation System
<div dir='rtl'>
    <p>مثال على <code>Netfilx</code> كيف تقترح افلام؟</p>
    <p>تقوم بعمل خوارزميه (<code>Algorithm</code>) لمقارنة سلوك المستخدمين</p>
    <p>فى هذا الدرس سوف نقوم بعمل خوارزميه بنفسنا لأقتراح الافلام بناءً على التقييمات</p>
</div>

## Prepare the data

In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [15]:
df = pd.DataFrame(
    {
        "Batman": [5, 4, None, 1],
        "Spider Man": [4, 5, None, 2],
        "Finding Nemo": [1, None, 5, 4],
        "Toy Store": [None, 4, 2, 5],
        "Tangled": [5, 3, None, 2]
    },
    index=["Ahmed", "Ali", "Sarah", "Mona"]
)
df

       Batman  Spider Man  Finding Nemo  Toy Store  Tangled
Ahmed     5.0         4.0           1.0        NaN      5.0
Ali       4.0         5.0           NaN        4.0      3.0
Sarah     NaN         NaN           5.0        2.0      NaN
Mona      1.0         2.0           4.0        5.0      2.0

## Data cleaning

In [16]:
df.isna().sum()

Batman          1
Spider Man      1
Finding Nemo    1
Toy Store       1
Tangled         1
dtype: int64

In [17]:
df.fillna(0, inplace=True)

       Batman  Spider Man  Finding Nemo  Toy Store  Tangled
Ahmed     5.0         4.0           1.0        0.0      5.0
Ali       4.0         5.0           0.0        4.0      3.0
Sarah     0.0         0.0           5.0        2.0      0.0
Mona      1.0         2.0           4.0        5.0      2.0

## Proceess the data
<div dir='rtl'>
    <p>لاحظنا ان العواميد تتكون من اسماء المشاهدين، ولكننا لا نريد ان نقارن المستخدمين، نريد ان نقارن الافلام لذالك نريد ان نعكس البيانات من <code>index</code> إلى <code>columns</code></p>
    <p>سوف نستخدم <code>T</code> وتعنى <code>Transpose</code> لقلب الجدول</p>
    <p></p>
</div>

In [18]:
df.T

              Ahmed  Ali  Sarah  Mona
Batman          5.0  4.0    0.0   1.0
Spider Man      4.0  5.0    0.0   2.0
Finding Nemo    1.0  0.0    5.0   4.0
Toy Store       0.0  4.0    2.0   5.0
Tangled         5.0  3.0    0.0   2.0

<p dir='rtl'>الان نريد ان نعرف نسبة التشابه لكل تقييم</p>

In [19]:
similarity_metrix = cosine_similarity(df.T)
similarity_metrix

array([[1.        , 0.96609178, 0.21428571, 0.48304589, 0.97622104],
       [0.96609178, 1.        , 0.27602622, 0.66666667, 0.94311913],
       [0.21428571, 0.27602622, 1.        , 0.69006556, 0.32540701],
       [0.48304589, 0.66666667, 0.69006556, 1.        , 0.53201592],
       [0.97622104, 0.94311913, 0.32540701, 0.53201592, 1.        ]])

In [21]:
dt = pd.DataFrame(similarity_metrix, index=df.columns, columns=df.columns)
dt

                Batman  Spider Man  Finding Nemo  Toy Store   Tangled
Batman        1.000000    0.966092      0.214286   0.483046  0.976221
Spider Man    0.966092    1.000000      0.276026   0.666667  0.943119
Finding Nemo  0.214286    0.276026      1.000000   0.690066  0.325407
Toy Store     0.483046    0.666667      0.690066   1.000000  0.532016
Tangled       0.976221    0.943119      0.325407   0.532016  1.000000

<p dir='rtl'>الان لنقم بعمل <code>function</code> صغيره لطباعة نسبة تشابه كل فيلم بناءً على اسم الفيلم</p>

In [11]:
def system_recommend_matching(movie_name: str) -> None: # Batman
    print(f"since you liked {movie_name} then we recommend:")
    print("-" * 50)
    
    # show all rows but skip the selected movie
    recommendations = dt[movie_name].sort_values(ascending=False)[1:]
    
    for movie, score in recommendations.items():
        print(f"{movie} (Match: {score:.2%})")

In [13]:
system_recommend_matching("Toy Store")

since you liked Toy Store then we recommend:
--------------------------------------------------
Finding Nemo (Match: 69.01%)
Spider Man (Match: 66.67%)
Batman (Match: 48.30%)

In [22]:
movie = input("Enter the movie name that you have watched: ") # Spider Man

system_recommend_matching(movie)

since you liked Tangled then we recommend:
--------------------------------------------------
Batman (Match: 97.62%)
Spider Man (Match: 94.31%)
Toy Store (Match: 53.20%)
Finding Nemo (Match: 32.54%)