# Recommendation System
<div dir='rtl'>
    <p>مثال على <code>Netfilx</code> كيف تقترح افلام؟</p>
    <p>تقوم بعمل خوارزميه (<code>Algorithm</code>) لمقارنة سلوك المستخدمين</p>
    <p>فى هذا الدرس سوف نقوم بعمل خوارزميه بنفسنا لأقتراح الافلام بناءً على التقييمات</p>
</div>

## Prepare the data

In [41]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [70]:
df = pd.DataFrame(
    {
        "Batman": [5, 4, None, 1],
        "Spider Man": [4, 5, None, 2],
        "Finding Nemo": [1, None, 5, 4],
        "Toy Store": [None, 4, 2, 5],
    },
    index=["Ahmed", "Ali", "Sarah", "Mona"]
)
df

       Batman  Spider Man  Finding Nemo  Toy Store
Ahmed     5.0         4.0           1.0        NaN
Ali       4.0         5.0           NaN        4.0
Sarah     NaN         NaN           5.0        2.0
Mona      1.0         2.0           4.0        5.0

## Data cleaning

In [43]:
df.isna().sum()

Batman          1
Spider Man      1
Finding Nemo    1
Toy Store       1
dtype: int64

In [44]:
df.fillna(0, inplace=True)

       Batman  Spider Man  Finding Nemo  Toy Store
Ahmed     5.0         4.0           1.0        0.0
Ali       4.0         5.0           0.0        4.0
Sarah     0.0         0.0           5.0        2.0
Mona      1.0         2.0           4.0        5.0

## Proceess the data
<div dir='rtl'>
    <p>لاحظنا ان العواميد تتكون من اسماء المشاهدين، ولكننا لا نريد ان نقارن المستخدمين، نريد ان نقارن الافلام لذالك نريد ان نعكس البيانات من <code>index</code> إلى <code>columns</code></p>
    <p>سوف نستخدم <code>T</code> وتعنى <code>Transpose</code> لقلب الجدول</p>
    <p></p>
</div>

In [46]:
df.T

              Ahmed  Ali  Sarah  Mona
Batman          5.0  4.0    0.0   1.0
Spider Man      4.0  5.0    0.0   2.0
Finding Nemo    1.0  0.0    5.0   4.0
Toy Store       0.0  4.0    2.0   5.0

<p dir='rtl'>الان نريد ان نعرف نسبة التشابه لكل تقييم</p>

In [47]:
similarity_metrix = cosine_similarity(df.T)
similarity_metrix

array([[1.        , 0.96609178, 0.21428571, 0.48304589],
       [0.96609178, 1.        , 0.27602622, 0.66666667],
       [0.21428571, 0.27602622, 1.        , 0.69006556],
       [0.48304589, 0.66666667, 0.69006556, 1.        ]])

In [54]:
dt = pd.DataFrame(similarity_metrix, index=df.columns, columns=df.columns)
dt

                Batman  Spider Man  Finding Nemo  Toy Store
Batman        1.000000    0.966092      0.214286   0.483046
Spider Man    0.966092    1.000000      0.276026   0.666667
Finding Nemo  0.214286    0.276026      1.000000   0.690066
Toy Store     0.483046    0.666667      0.690066   1.000000

<p dir='rtl'>الان لنقم بعمل <code>function</code> صغيره لطباعة نسبة تشابه كل فيلم بناءً على اسم الفيلم</p>

In [59]:
def system_recommend_matching(movie_name: str) -> None:
    print(f"since you liked {movie_name} then we recommend:")
    print("-" * 50)
    
    # show all rows but skip the selected movie
    recommendations = dt[movie_name].sort_values(ascending=False)[1:]
    
    for movie, score in recommendations.items():
        print(f"{movie} (Match: {score:.2%})")

In [61]:
system_recommend_matching("Batman")

since you liked Batman then we recommend:
--------------------------------------------------
Spider Man (Match: 96.61%)
Toy Store (Match: 48.30%)
Finding Nemo (Match: 21.43%)

In [73]:
movie = input("Enter the movie name that you have watched: ") # Spider Man

recommended_movie = dt[movie].sort_values(ascending=False)[1:] * 100
recommended_movie

Batman          96.609178
Toy Store       66.666667
Finding Nemo    27.602622
Name: Spider Man, dtype: float64

In [74]:
recommended_movie.index[0]

'Batman'